#routes non authentifiées
page_accueil:
    path:     /
    defaults: { _controller: "BZControllerBundle:Default:index" }
    
page_vide:
    path:     /page_vide
    defaults: { _controller: "BZControllerBundle:Default:page_vide" }

    
#routes authentifiées
bz_controller:
    resource: "@BZControllerBundle/Resources/config/routing.yml"
    prefix:   /bz_data
    
bz_user:
    resource: "@BZUserBundle/Resources/config/routing.yml"
    prefix:   /bz_user

fos_user_security_login:
    path:     /login
    defaults: { _controller: "FOSUserBundle:Security:login" }
    
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /bz_user
    
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#    prefix:   /
#
#    
#fos_user_registration_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#    
